language: python
python:
  - 3.6
  # - 3.7-dev # Fail with:
  # KeyError: <Task finished coro=<BaseEventLoop.run_in_executor() done, defined at /opt/python/3.7-dev/lib/python3.7/asyncio/base_events.py:653> result=False>
  # - 3.7
  # - pypy3.6

git:
  depth: 10

install:
  - python -m pip install poetry
  - make installdeps

script:
  - make check

notifications:
  email: 8slashes+travis-ci@gmail.com
