language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy3
install:
  - pip install pipenv
  - pipenv install --dev
script: pipenv ./test/run.sh
notifications:
  email: 8slashes+travis-ci@gmail.com
