# Generated by Django 2.1.4 on 2018-12-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='date created')),
                ('updated_at', models.DateTimeField(verbose_name='date updated')),
                ('markdown', models.CharField(default='', max_length=5000)),
                ('path', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
