# Generated by Django 2.1.4 on 2018-12-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='markdown',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
